# Generated by Django 5.2.7 on 2025-11-02 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Напр., 'Массажный', 'Косметологический'", max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип кабинета',
                'verbose_name_plural': 'Типы кабинетов',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spa_open_time', models.TimeField(default='09:00', verbose_name='Время открытия')),
                ('spa_close_time', models.TimeField(default='21:00', verbose_name='Время закрытия')),
                ('buffer_time_minutes', models.PositiveIntegerField(default=15, help_text='Время на уборку (в минутах) между бронями.', verbose_name='Буферное время (мин)')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Напр., 'Кабинет 1', 'VIP Комната'", max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('cabinet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cabinets', to='booking.cabinettype', verbose_name='Тип кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Напр., 'Тайский массаж'", max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('required_cabinet_types', models.ManyToManyField(help_text='Какие типы кабинетов нужны для этой услуги.', to='booking.cabinettype', verbose_name='Требуемые типы кабинетов')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_suffix', models.CharField(help_text="Напр., '60 мин', '90 мин', 'Интенсив'", max_length=100, verbose_name='Суффикс названия')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Длительность (мин)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='booking.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Вариант услуги',
                'verbose_name_plural': 'Варианты услуг',
            },
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('services_can_perform', models.ManyToManyField(help_text='Какие услуги может выполнять этот специалист.', to='booking.service', verbose_name='Может выполнять услуги')),
                ('user', models.OneToOneField(help_text='Аккаунт для входа в систему.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль специалиста',
                'verbose_name_plural': 'Профили специалистов',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200, verbose_name='Имя гостя')),
                ('guest_room_number', models.CharField(blank=True, max_length=20, verbose_name='Номер комнаты гостя')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(editable=False, help_text='Рассчитывается автоматически: start_time + duration + buffer.', verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждено'), ('completed', 'Выполнено'), ('canceled', 'Отменено')], default='confirmed', max_length=20, verbose_name='Статус')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.cabinet', verbose_name='Кабинет')),
                ('service_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.servicevariant', verbose_name='Вариант услуги')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.specialistprofile', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Окончание работы')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='booking.specialistprofile', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
                'unique_together': {('specialist', 'day_of_week')},
            },
        ),
    ]
