# Generated by Django 5.2.7 on 2025-11-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтверждено'), ('paid', 'Оплачено'), ('completed', 'Выполнено'), ('canceled', 'Отменено')], default='confirmed', max_length=20, verbose_name='Статус'),
        ),
    ]
