# Generated by Django 5.2.7 on 2025-11-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='send_email_notifications',
            field=models.BooleanField(default=True, help_text='Отправлять email-уведомления специалистам о новых бронированиях', verbose_name='Email уведомления'),
        ),
    ]
