# Generated by Django 5.2.7 on 2025-11-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_cabinetclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enable_booking_copy_shortcuts',
            field=models.BooleanField(default=True, help_text='Разрешить копирование/вставку бронирований с помощью горячих клавиш на календаре', verbose_name='Горячие клавиши копирования брони'),
        ),
    ]
