# Generated by Django 5.2.7 on 2025-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_systemsettings_enable_booking_copy_shortcuts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Не подтверждено'), ('confirmed', 'Подтверждено'), ('paid', 'Оплачено'), ('completed', 'Выполнено'), ('canceled', 'Отменено')], default='confirmed', max_length=20, verbose_name='Статус'),
        ),
    ]

