# Generated by Django 5.2.7 on 2025-11-17 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_add_unconfirmed_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(blank=True, help_text='ID бронирования до удаления', null=True, verbose_name='ID оригинального бронирования')),
                ('booking_data', models.JSONField(help_text='Полные данные удаленного бронирования в формате JSON', verbose_name='Данные бронирования')),
                ('series_id', models.IntegerField(blank=True, help_text='ID серии, если бронирование входило в серию', null=True, verbose_name='ID серии')),
                ('series_data', models.JSONField(blank=True, help_text='Данные серии, если бронирование входило в серию', null=True, verbose_name='Данные серии')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата удаления')),
                ('deletion_reason', models.CharField(blank=True, help_text='Опциональная причина удаления', max_length=500, verbose_name='Причина удаления')),
                ('deletion_scope', models.CharField(choices=[('single', 'Одиночное бронирование'), ('series', 'Серия бронирований')], default='single', max_length=20, verbose_name='Область удаления')),
                ('restored', models.BooleanField(default=False, help_text='Было ли бронирование восстановлено', verbose_name='Восстановлено')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Удалено пользователем')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Восстановлено пользователем')),
            ],
            options={
                'verbose_name': 'Удаленное бронирование',
                'verbose_name_plural': 'Удаленные бронирования',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['original_id'], name='booking_del_origina_527f92_idx'), models.Index(fields=['deleted_at'], name='booking_del_deleted_63cfcc_idx'), models.Index(fields=['restored'], name='booking_del_restore_758b9c_idx'), models.Index(fields=['series_id'], name='booking_del_series__56a942_idx')],
            },
        ),
    ]
