# Generated by Django 5.2.7 on 2025-11-24 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_deletedbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создано'), ('updated', 'Обновлено'), ('deleted', 'Удалено'), ('status_changed', 'Изменен статус'), ('time_changed', 'Изменено время'), ('specialist_changed', 'Изменен специалист'), ('cabinet_changed', 'Изменен кабинет'), ('service_changed', 'Изменена услуга'), ('series_created', 'Создана серия'), ('series_updated', 'Обновлена серия'), ('duplicated', 'Скопировано')], max_length=50, verbose_name='Действие')),
                ('message', models.TextField(help_text='Описание действия', verbose_name='Сообщение')),
                ('old_values', models.JSONField(blank=True, help_text='Значения полей до изменения (JSON)', null=True, verbose_name='Старые значения')),
                ('new_values', models.JSONField(blank=True, help_text='Значения полей после изменения (JSON)', null=True, verbose_name='Новые значения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='booking.booking', verbose_name='Бронирование')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог бронирования',
                'verbose_name_plural': 'Логи бронирований',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', '-created_at'], name='booking_boo_booking_2ae57c_idx'), models.Index(fields=['action'], name='booking_boo_action_c7f80a_idx'), models.Index(fields=['user'], name='booking_boo_user_id_8b95ad_idx')],
            },
        ),
    ]
