# Generated by Django 5.2.7 on 2026-01-26 07:57

import django.db.models.deletion
from django.db import migrations, models
import re


def normalize_guest_name(name):
    """Нормализует имя гостя для сравнения"""
    if not name:
        return ""
    normalized = re.sub(r'\s+', ' ', name.strip())
    words = normalized.split()
    capitalized_words = []
    for word in words:
        if word:
            capitalized = word[0].upper() + word[1:].lower() if len(word) > 1 else word.upper()
            capitalized_words.append(capitalized)
    return ' '.join(capitalized_words)


def migrate_guest_names_to_guests(apps, schema_editor):
    """Переносит данные из guest_name в модель Guest"""
    Guest = apps.get_model('booking', 'Guest')
    Booking = apps.get_model('booking', 'Booking')
    
    # Получаем все уникальные имена гостей
    bookings = Booking.objects.all()
    guest_name_map = {}  # normalized_name -> Guest instance
    
    for booking in bookings:
        if not booking.guest_name:
            continue
        
        normalized = normalize_guest_name(booking.guest_name)
        if not normalized:
            continue
        
        # Создаем или получаем Guest
        if normalized not in guest_name_map:
            guest, created = Guest.objects.get_or_create(
                normalized_name=normalized,
                defaults={'display_name': booking.guest_name}
            )
            guest_name_map[normalized] = guest
        else:
            # Если уже есть, обновляем display_name если текущий более "правильный"
            guest = guest_name_map[normalized]
            # Сохраняем первый вариант как display_name (или можно выбрать самый частый)
            if guest.display_name != booking.guest_name:
                # Можно оставить первый вариант или выбрать более "правильный"
                pass
        
        # Связываем бронирование с гостем
        booking.guest = guest_name_map[normalized]
        booking.save(update_fields=['guest'])


def reverse_migrate_guests_to_names(apps, schema_editor):
    """Обратная миграция: копирует display_name обратно в guest_name"""
    Booking = apps.get_model('booking', 'Booking')
    
    for booking in Booking.objects.filter(guest__isnull=False):
        booking.guest_name = booking.guest.display_name
        booking.save(update_fields=['guest_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_bookinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(help_text='Временное поле для обратной совместимости (deprecated)', max_length=200, verbose_name='Имя гостя'),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(db_index=True, help_text='Имя для поиска и сравнения (автоматически нормализуется)', max_length=200, unique=True, verbose_name='Нормализованное имя')),
                ('display_name', models.CharField(help_text='Имя как его ввел пользователь (для отображения)', max_length=200, verbose_name='Отображаемое имя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
                'ordering': ['normalized_name'],
                'indexes': [models.Index(fields=['normalized_name'], name='booking_gue_normali_3c5a91_idx'), models.Index(fields=['display_name'], name='booking_gue_display_bdf4db_idx')],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(blank=True, help_text='Связанный гость (новая система)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.guest', verbose_name='Гость'),
        ),
        migrations.RunPython(
            migrate_guest_names_to_guests,
            reverse_migrate_guests_to_names,
        ),
    ]
