# Generated by Django 5.2.7 on 2026-05-26 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_add_booking_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOAPNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('subjective', models.TextField(blank=True, help_text='Что говорит клиент', verbose_name='Жалобы клиента (S)')),
                ('objective', models.TextField(blank=True, help_text='Тонус мышц, триггеры', verbose_name='Объективные показатели (O)')),
                ('assessment', models.TextField(blank=True, help_text='Результаты диагностики', verbose_name='Оценка специалиста (A)')),
                ('plan', models.TextField(blank=True, help_text='Рекомендации по процедурам', verbose_name='План дальнейшей терапии (P)')),
                ('body_map_data', models.JSONField(blank=True, default=dict, verbose_name='Разметка триггерных точек')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soap_notes', to='booking.guest', verbose_name='Гость')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.specialistprofile', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'SOAP карта гостя',
                'verbose_name_plural': 'SOAP карты гостей',
                'ordering': ['-created_at'],
            },
        ),
    ]
